builders:
  mini_data:
    target: ":mini_data"
    import: "package:mini_data/mini_data.dart"
    builder_factories: ["copyWith"]
    build_extensions: {".dart": ["mini_data.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]