targets:
  $default:
    builders:
      mini_data_gen:
        enabled: true
        generate_for:
          exclude:
            - test
            - example
          include:
            - test/gen_*

builders:
  copy_with:
    import: "package:mini_data_gen/mini_data_gen.dart"
    builder_factories: [ "copyWithBuilder" ]
    build_extensions: { ".dart": [ ".copy_with.g.dart" ] }
    auto_apply: dependents
    build_to: cache
  merge:
    import: "package:mini_data_gen/mini_data_gen.dart"
    builder_factories: [ "mergeBuilder" ]
    build_extensions: { ".dart": [ ".merge.g.dart" ] }
    auto_apply: dependents
    build_to: cache
