targets:
  $default:
    builders:
      mini_data_gen:
        options:
          generate_copy_with: true
          generate_merge: true

builders:
  mini_data_gen:
    import: "package:mini_data_gen/mini_data_gen.dart"
    builder_factories: ["createCopyWithBuilder", "createMergeBuilder"]
    build_extensions: {".dart": [".g.dart"]}
    auto_apply: dependents
    is_optional: true
