targets:
  $default:
    builders:
      mini_data_gen:
        enabled: true
        generate_for:
          exclude:
            - test
            - example
          include:
            - test/gen_*

builders:
  mini_data_gen:
    target: ":mini_data_gen"
    import: "package:mini_data_gen/mini_data_gen.dart"
    builder_factories: ["copyWith"]
    build_extensions: {".dart": ["copy_with_extension_gen.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]

  copy_with:
    import: "package:mini_data_gen/src/mini_copy_with_generator.dart"
    builder_factories: [ "copyWithBuilder" ]
    build_extensions: { ".dart": [ ".copy_with.g.dart" ] }
    auto_apply: dependents
    build_to: cache
  merge:
    import: "package:mini_data_gen/src/mini_merge_generator.dart"
    builder_factories: [ "mergeBuilder" ]
    build_extensions: { ".dart": [ ".merge.g.dart" ] }
    auto_apply: dependents
    build_to: cache
