targets:
  $default:
    builders:
      mini_data_gen:
        enabled: true
        generate_for:
          exclude:
            - test
            - example
          include:
            - test/gen_*

builders:
  mini_copy_with:
    import: "package:mini_data_gen/mini_data_gen.dart"
    builder_factories: ["CopyWithGenerator"]
    build_extensions: { ".dart": [".g.dart"] }
    auto_apply: dependents
    build_to: cache
    defaults:
      generate_for:
        include:
          - lib/**/*.dart
      options: { }
  mini_merge:
    import: "package:mini_data_gen/mini_data_gen.dart"
    builder_factories: ["MergeGenerator"]
    build_extensions: { ".dart": [".g.dart"] }
    auto_apply: dependents
    build_to: cache
    defaults:
      generate_for:
        include:
          - lib/**/*.dart
      options: { }